### PR TITLE
 Update idle.js w/ best zone, ... 

### PR DESCRIPTION
**Pull request by Harest**
- Credit to Meepen for the GestBestZone function (slightly edited here)  
- Prevented infinite retries to report a score.  
- Enabled the possibility to automatically join the best zone at launch (true by default)  
- Automatically switch to a new best zone if the current zone is completed.

### CODE REVIEW

**Review by asdfCYBER — APPROVED** [review]

**Comment by ensingm2** [comment]
Nice! Thank you.

**Comment by Harest** [comment]
Np, glad to help. I liked this script more than the others because there were no planet switch. And i had the same base idea but i didn't bother to do it properly yesterday :p. So i just used the `CEnemyManager.prototype.BuildEnemy = function(){};` until then.  
Thanks for doing it.

**Comment by Harest** [comment]
I think i forgot a major issue here. We don't update the grid. It should be added somewhere, before switching to a new zone if the current one is completed. Otherwise it'll probably try to switch to the same zone.

**Comment by ensingm2** [comment]
If you're pulling from window.gGame.m_State.m_PlanetData.zones, I would imagine the default game scripts would keep that array up to date. It's definitly worth keeping in mind though. I'll take a look and verify that's actually the case when I have free time tonight.

**Comment by Harest** [comment]
Yeah i'd have hoped so too, but since the map UI is never refreshed automatically, and that i don't see any others requests that the ones we do with the script... I'll check if i see an url to get the zones updates easily.

**Comment by ensingm2** [comment]
Ah, damn. If you're not too busy and _**want**_ to fix it feel free, otherwise I'll take a look when I get off work.

**Comment by Harest** [comment]
I've it ready, i'll make a pull req for it.

**Pull request merged**
