### PR TITLE
Chrome-Tampermonkey fixes

### PR DESCRIPTION
**Pull request by alex-vg**
fixes 
- INJECT_disable_animations not found
- highestDifficulty undefined
- gui undefined

removed some spaces

removed unneeded and unreachable duplicated code

### CODE REVIEW

**Comment by ensingm2** [comment]
What chrome version are you running? I've been testing in Chrome and haven't run into any of these errors myself.

**Comment by alex-vg** [comment]
Forgot to mention that I'm using tampermonkey, which is not registering global vars on window.
Anyway, vars should not be implicitly treated as globals. (INJECT_disable_animations, gui)
Also highestDifficulty can be exactly zone.difficulty, which is not handled and results in errors.

**Comment by ensingm2** [comment]
Can I see your Tampermonkey script that's running this and producing errors? I'd like to try myself, if possible.

Also, if the globals were erroring out, do the others not also run into that issue? I feel like if these get fixed the script will error out near after, which is why I'd like to test.

**Comment by ROMB** [comment]
I don't really like that solution. Instead of exposing gui to the window, we should make it initialized locally inside the script and fix calls to use that local variable instead of window.gui.

**Comment by alex-vg** [comment]
How do you want to call a local function from an onclick event?
Anyway, I'm forking private.

**Comment by ROMB** [comment]
Because if variable is initialized before local function was created it will be available for local function too. Check updated master branch, it already works with  tampermonkey using local variable.

**Comment by alex-vg** [comment]
onclick="INJECT_disable_animations()"

That is still global. No closures are built for the template. Wrap everything with 'use strict' and you can detect that.

**Comment by ROMB** [comment]
Yep, I agree with that particular one, not with gui one though. Best way to fix it would be to replace `onclick="INJECT_disable_animations()"` with something like
```JavaScript
$J('#disableAnimsBtn').click(function() {
  INJECT_disable_animations();
});
```

**Pull request closed without merging**
