### PR TITLE
Enable to automatically switch planet

### PR DESCRIPTION
**Pull request by Harest**
#22   
Not yet 100% functional as there's a CORS problem in GetBestPlanet() when we request info on active and not captured planets to calculate their score, but it doesn't prevent the script to run properly afaik.

### CODE REVIEW

**Comment by ensingm2** [comment]
Alright. I'll probably wait to merge this until there's a functional new feature if that's cool.

If it helps, I'm about 90% done with restructuring things to allow manual movement between zones/planets. It'll include calls to leave & join planets through the UI & update script stuff. Might make your life easier to just find the "best" one and call those.

**Comment by Harest** [comment]
Sure. For now i just don't know why there's these network errors. I don't think it's related to the script. Sometimes it loads the data, sometimes it just returns an empty response. Nothing i can do here. Except retrying to get the data but it'll do so anyway in 5 more rounds so i guess it's better to just let it that way to not spam the Valve's servers.  
I just saw i forgot something in the planet score calculation... i'll fix it too. The rest is independant of my will.

**Comment by ensingm2** [comment]
Just pushed a pretty significant number of changes, including the ability to skip between planets (mostly) without issue. Worth trying my functions if you're still stuck getting server errors

**Comment by Harest** [comment]
Yeah there's still CORS errors that i somehow managed with preventing to switch planet if there 2 or more errors while fetching planets. Gonna check out your changes and see how it goes.

**Comment by Harest** [comment]
Well, you managed manual actions while i tried to automatize more ^^. Except the change on the max_retries and the removal of SwitchNextZone() after too many errors with a "please refresh", seems good to me.  
So dunno if you want to merge or not. Maybe i should try to put a delay between each planet request to see if there's still errors or not, like 1s.

**Comment by ensingm2** [comment]
I'll try and poke around a bit.

**Comment by Harest** [comment]
For now Steam is kinda down anyway, it'll be difficult to test anything, the base script just stops working. `504 Gateway Timeout`.  
Tell me if you want me to manage conflicts or not.

**Comment by ensingm2** [comment]
Would you mind? I resolved the conflicts on my end, and things seem to be working, but I don't really know how to test the autoswitch components.

**Comment by Harest** [comment]
Should be good?  
Up to you to set the auto switch to true by default (`auto_switch_planet.active`). Considering how unstable the steam api is, i'd rather see it set to false and anyone can set it to true. It works, but it's not 100% reliable unfortunately. I tried by best to avoid issues due to network errors.  
I modified how network issues are managed too so it's automatic after max_retries is reached instead of the "please refresh" message.  Feel free to make it an option or something, i'd rather see the script continue functioning imo.  
_Currently testing the script with both your modifications and mine (with auto planet switch currently at false), and it works so far. I played for a while with it set to true and it worked too. Made several fixes for it to work the best it could._

**Comment by ensingm2** [comment]
Thanks! I'm gonna look into this in a minute, want to try to merge our changes so any auto-swaps reflect in the game interface as well. Hoping it shouldn't be too hard to reset the game state.

**Comment by ensingm2** [comment]
So calling CheckSwitchBetterPlanet() now works with the new planet switching scripts I made, so it'll go through the UI and wait for updates, and show map, etc. I am getting those errors somewhat periodically though. I also need to look into a way to have those same scripts swap planets when animations are disabled.

**Comment by Harest** [comment]
Nice. Which errors (CORS ones due to empty responses for no appearing reason ?) ? Saw you fixed the attempt_no missing here and there too since the removal of current_retry.  
I think you removed a start_round in the SwitchNextZone() function that was required btw if next_zone !== undefined & next_zone == target_zone. That was one of the commits i did because afair i got stuck out of a round due to its absence.

**Comment by ensingm2** [comment]
Yeah, it's CORS issues, which makes me think it's a steam-side server config issue.

So to my knowledge SwitchNextZone and CheckSwitchBetterPlanet are only ever called when the final responses error out enough times. Assuming that's the case, if we errored out to max_attempts, and still haven't found a better zone(next_zone == target_zone), it **should** hang. Otherwise, SwitchNextZone will continue to try to select the problem zone, it will error out max_attempts times, which will trigger SwitchNextZone again and infinite loop. That's why I removed that start_round.

Feel free to correct me if I'm mistaken though.

**Comment by Harest** [comment]
It's also called in CheckSwitchBetterPlanet() if the best planet = current one. So maybe switching it with a start_round there instead and like you said, avoiding an infinite loop.

**Comment by ensingm2** [comment]
Same scenario there, I believe (CheckSwitchBetterPlanet is only ever called in those same spots). Only time you hit that case is if the "best" zone has already been tried and failed. Just at a planet+zone level.

Exception is code block at 180, but I **believe** that only triggers when next_zone won't equal target_zone, since it's expecting to switch planets.

**Comment by Harest** [comment]
Also called every 6 rounds if the current difficulty is < to the wanted one. If we check for best planet and it's the current one, and then we don't start a round everything is stopped.

**Comment by ensingm2** [comment]
Ah, ok yeah that's an issue then. Thanks for the clarification!

**Comment by Harest** [comment]
Np. And thinking about it that's also why there's SwitchNextZone() in CheckSwitchBetterPlanet() if best planet = current one. If the auto planet switch is active it first check if there's a better planet and if not it try to switch zone.

**Comment by ensingm2** [comment]
Gonna merge this in, looks like it's mostly working, barring the issues with CORS. Will leave it disabled by default for the time being, until hopefully either Steam gets their server stuff figured out, or we find a workaround.

**Comment by Harest** [comment]
Sounds about right yes. Maybe we could also implement a quick way at some point to call `CheckSwitchBetterPlanet(true)` in the UI. So whether or not the auto switch is activated, you can check if there's eventually a new planet to go.

**Comment by ensingm2** [comment]
Agreed, I've just been calling it through console but if it's not done automatically then some other way would be decent. Hoping it can get enabled by default soonish though.

**Comment by Harest** [comment]
I didn't try yet to delay requests to fetch the zones of the 5 active planets. It may solve the issue. I'll take a break for now ^^. If anyone wants to give it a try, otherwise i'll probably later on.

**Pull request merged**
