### PR TITLE
Add Tampermonkey script headers

### PR DESCRIPTION
**Pull request by ROMB**
https://tampermonkey.net/documentation.php

### CODE REVIEW

**Comment by ensingm2** [comment]
Currently the script doesn't support being pasted to the main menu, so autorunning it via tampermonkey doesn't work without leaving it disabled and manually running the script once you click through.

This should probably be fixed at some point, though. Leaving this open for now.

**Comment by ROMB** [comment]
Yep, I have the fix already. Will it be ok to push it with the same PR?

**Comment by ensingm2** [comment]
Yeah, I'd just commit it to this PR and I'll merge them at once, once I can verify it's working and test a little.

**Comment by ROMB** [comment]
Done. Latest commit just checks the state, clicks "start" button and properly loads planet selection.

**Comment by ensingm2** [comment]
Current changes break the script being pasted in the Planet Selector or Battle Map, unfortunately. Since that is what people are used to doing, we need to keep support for manual pasting to those locations.

**Comment by ROMB** [comment]
Here is easy fix for that.

**Comment by ensingm2** [comment]
Can you confirm the changes I've made work for you as well? I did a cleaner fix for manual pasting, and disabled script auto-updating.

**Comment by formigao** [comment]
can you post at the main page a working Tampermonkey script ? im trying to make it work manually without success

**Comment by ensingm2** [comment]
@formigao that's what this PR is. feel free to grab the [file currently being reviewed here ](https://raw.githubusercontent.com/ROMB/saliengame_idler/0ad341a93c4f282f131a6ca9025d6d82c98df5f1/idle.js) if you don't want to wait for it to be merged back to master. Seems to be working, but no gurantees.

**Comment by ROMB** [comment]
Yep, looks perfectly working.

**Pull request merged**
