### PR TITLE
Real-time updates for Lvl Up In

### PR DESCRIPTION
**Pull request by Jap2-0**
This makes the "Lvl Up In" field update in real-time.

### CODE REVIEW

**Comment by Jap2-0** [comment]
Also note that this includes everything from my previous pull request about this function, so this kind of deprecates that.

**Comment by ensingm2** [comment]
When issuing Pull Requests, please try to isolate new features & changes as much as possible, as this PR is dependent on another that has been closed.

For small changes, please also consider squashing commits and use git's merge feature rather than manually syncing changes in order to keep things neat.

**Comment by Jap2-0** [comment]
Apologies, I'm not really familiar with Github - also, I tried to merge, however it wouldn't let me.

I can create this separately from my previous one, if you want (it shouldn't have any dependencies on that)

About my previous Pull Request: ceil is actually making it more accurate.  What you have now would give you the exact time it would finish if you were getting experience at a constant rate - but you're not.  You get a set amount (600, 1200, or 2400) about every two minutes.  That means that the current estimate could be up to nearly two minutes off (relatively minor, but still an inaccuracy - which will probably be more obvious if this is implemented).  That pull request accounted for that by finding how many games until you'll level up, rounding that figure up, and then multiplying again.  Here's an example:

You have 6,600 experience.  You need 14,400 experience for the next level.  You are playing hard tiles, so you get 2,400 experience each.  The current algorithm would do the following:

	const missingExp(7800) = gPlayerInfo.next_level_score(14400) - gPlayerInfo.score(6600);
	const nextScoreAmount(2400) = get_max_score(target_zone)(2400);
	const roundTime(111) = resend_frequency(110) + update_length(1);

	const secondsLeft(360.75) = missingExp(7800) / nextScoreAmount(2400) * roundTime(111);

	return secondsLeft(360.75);

 
However, after 360.75 seconds, you would only have completed 3 games, gaining 7,200 experience for a total of 13,800.  You would not level up until you finished the next game, at 444 seconds (when you would have 16,200 experience).  My pull request would do the following:

	const nextScoreAmount(2400) = get_max_score(target_zone)(2400);
	const missingExp(9600) = Math.ceil((gPlayerInfo.next_level_score(14400) - gPlayerInfo.score(6600))(7800) / nextScoreAmount(2400))(3.25->4) * nextScoreAmount(2400);
	const roundTime(111) = resend_frequency(110) + update_length(1);

	const secondsLeft(444) = missingExp(9600) / nextScoreAmount(2400) * roundTime(111);

	return secondsLeft(444);


That said, yes, you can't guarantee that you'll maintain the current difficulty level, which would affect it significantly more if it changes, but that is much more difficult to account for.

**Comment by ensingm2** [comment]
Yeah, you're completely right, my fault (Sorry, been staring at way too much code the past couple days between this and my job, eyes starting to glaze over). Thanks for taking the time to re-explain it. If you'd like it issue another pull request, feel free. I'm re-opening your other PR though as I think it's clean enough.

Please try to keep the PR concise if possible, though, and squash/remove unnecessary commits.

**Comment by Jap2-0** [comment]
I think I made it work with one commit (although I'm not entirely sure how this all works), and submitted that as another pull request.  I'm more than happy to explain my reasoning - I think we all have moments like that (I forgot how order of operations worked earlier, so I'm by no means exempt).

**Pull request closed without merging**
