### PR TITLE
fix bug where game stays in already completed zone

### PR DESCRIPTION
**Pull request by Zazcallabah**
refresh grid data before getting best zone
use getbestzone each time we start a new game
auto restart after a while if we see an error

### CODE REVIEW

**Comment by Zazcallabah** [comment]
This should fix #25

**Comment by ensingm2** [comment]
Sorry, but could you clarify on your changes here? I looked through them and noticed the following:

* The changes lines 228:235 seem to just endlessly query the steam servers if an error is encountered, ignoring the max_retries that we put in place.
* INJECT_restart_round I believe would cause additional issues, as if you're in a current game and it's called, it clears the current_game_id, making the script believe it's no longer in a game, which will skip it leaving and result in the error we're trying to fix.
* Refreshing grid data in GetBestZone is probably a good idea, but does not currently have a functional effect, as INJECT_update_grid() is called on the line right before GetBestZone().

Please feel free to correct me if I'm mistaken though!

**Comment by Zazcallabah** [comment]
In reverse order:

I added a call to GetBestZone in in INJECT_restart_round instead of using the previous used zone - because previous zone may be completed already. Thus it needs to refresh its own data. Or we could move the refresh into restart round as well, but this felt cleaner.

Restart round is only used to restart the game after an error or after a current game has finished. But if you don't, then yes we will have the problem you describe. Will we have a similar problem in the opposite direction if we restart a game without clearing current_game_id and the api doesn't expect us to leave? Should we error-check the response from INJECT_leave_round?

As for the endless loop, yes. But not without first trying to start a whole new game, possibly in a different zone. Note that if there is an actual problem, you will hit the wall when you try to join the next game. Has this loop ever worked, by the way? Because over here it only ever works the first time, or fails all five requests.

BTW, CEST here, so I need to sleep now. I'll be back in a few hours. :)

**Comment by ensingm2** [comment]
**GetBestZone:** Ok, that makes sense so it will indeed matter, but only if restart_round is added. See below. (I do agree that it's best the call be moved from its old location to where you have it in GetBestZone for code cleanliness though)

**Restart_round:** I'm not entirely sure we need this function:

* `UpdateNotificationCounts()` - I'm not sure is actually needed for anything (That's my bad, I think I added it when I was messing with UI stuff and committed it by accident? I'm unsure.)
* `current_game_id = undefined` - If a round is finished, this var is already set to undefined in leave_round. In the case of errors attempting to report score, The user is still technically in the game server-side, and they're expecting you to send a leave request. This is handled by start_round, but _**only**_ if current_game_id is set. Setting current_game_id to undefined right before calling start_zone produces more errors if you're still registered to a game server-side.
* `start_round()` - Since this is the only line remaining, it can be used instead of the restart_round() call.

**Loop:** You just mean restarting a single round? Yeah it's worked for most of us for a long time now, barring the odd issue or server-hiccup. Are you running into consistent issues with it? And the idea of max_retries was just so that if you got stuck in an error loop while afk overnight, you wouldn't be hammering valve's servers nonstop. We want to be nice if we can be.

**Comment by ensingm2** [comment]
Actually, turns out I'm super dumb and there _**is**_ an issue with the looping here. I believe it's actually stemming from not using callbacks and waiting for the existing leave_round functions to return before continuing on, leading to issues. If that is indeed the solution, it's probably better to fix it there, as it'll crop up in future spots as well.

**Comment by ensingm2** [comment]
Believe I've fixed this with the following commit:
8a3a7d4c926ed43bd585f6686dbf93ef406e320b.

If you still believe there's an issue, feel free to let me know.

**Comment by Zazcallabah** [comment]
Yeah, that looks fine. I suppose time will tell :)

**Pull request closed without merging**
