### PR TITLE
GUI and search best zone algorithm upgraded

### PR DESCRIPTION
**Pull request by JeanPaulLucien**
Also I tryid to create a checkbox to disable calculate the estimate time to next level. Somebody can fixed it. 

Tested. Works well.

### CODE REVIEW

**Comment by JeanPaulLucien** [comment]
https://github.com/ensingm2/saliengame_idler/issues/79 was fixed

**Comment by JeanPaulLucien** [comment]
Found that my if is not right fully. Fixed it. Now it found the best zone correctly.

**Comment by ensingm2** [comment]
Please try to limit commits to working changes, and if possible, separate different changes into different pull requests. That way, if there is an issue with one change, the others can still be added.

**Comment by JeanPaulLucien** [comment]
@ensingm2 , how to do it? Because Github add each commits in this pull request when I do commit in my master.

**Comment by ensingm2** [comment]
You'll need to use branches and issue pull requests from those. I will say though, almost all of these changes are minor syntax changes, id renames, and fixes to changes you made. They will likely not be merged in.

**Pull request closed without merging**
